/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Produto;
import model.ProdutoTableModel;

/**
 *
 * @author douglas
 */
public class TelaVendas extends javax.swing.JFrame {
    public static String total = "0";

    /**
     * Creates new form NewJFrame
     * @return 
     */
    public String getTotal() {
        return total;
    }

    public void setTotal(String total) {
        this.total = total;
    }
    
  
    ProdutoTableModel tableModel = new ProdutoTableModel();
    
    
    public TelaVendas() {
        initComponents();
        jTProdutos.setModel(tableModel);
    }
    
    private void adicionarProduto(String nome, float valor){
        Produto p = new Produto();
        p.setNome(nome);
        p.setValor(valor);
        tableModel.addRow(p);
        float soma = calcularTotal();
        lblTotal.setText(Float.toString(soma));
    }

    private float calcularTotal(){  
        return tableModel.getSoma();
    }
    
    private float subtrairTotal(){
        float subtrair = 0;
        for(int i=0; i < tableModel.getRowCount(); i++){
            if(i == jTProdutos.getSelectedRow()){
                subtrair =  (float) tableModel.getValueAt(i, 1);
            }
        }
        float r =  calcularTotal() - subtrair;
        lblTotal.setText(Float.toString(r));
        return r;
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiaHamburg = new javax.swing.JTabbedPane();
        painelCarne = new javax.swing.JPanel();
        btnCarne2 = new javax.swing.JButton();
        btnCarne3 = new javax.swing.JButton();
        btnCarne1 = new javax.swing.JButton();
        txtCarne1 = new javax.swing.JLabel();
        txtCarne2 = new javax.swing.JLabel();
        txtCarne3 = new javax.swing.JLabel();
        btnCarne7 = new javax.swing.JButton();
        btnCarne4 = new javax.swing.JButton();
        btnCarne6 = new javax.swing.JButton();
        btnCarne5 = new javax.swing.JButton();
        btnCarne8 = new javax.swing.JButton();
        txtCarne4 = new javax.swing.JLabel();
        txtCarne5 = new javax.swing.JLabel();
        txtCarne6 = new javax.swing.JLabel();
        txtCarne7 = new javax.swing.JLabel();
        txtCarne8 = new javax.swing.JLabel();
        btnCarne9 = new javax.swing.JButton();
        btnCarne10 = new javax.swing.JButton();
        txtCarne9 = new javax.swing.JLabel();
        txtCarne10 = new javax.swing.JLabel();
        painelFrango = new javax.swing.JPanel();
        btnFrango1 = new javax.swing.JButton();
        btnFrango2 = new javax.swing.JButton();
        btnFrango3 = new javax.swing.JButton();
        txtHamburgFrango1 = new javax.swing.JLabel();
        txtHamburgFrango2 = new javax.swing.JLabel();
        txtHamburgFrango3 = new javax.swing.JLabel();
        painelSemCarne = new javax.swing.JPanel();
        btnSemCarne1 = new javax.swing.JButton();
        txtSemCarne1 = new javax.swing.JLabel();
        painelKids = new javax.swing.JPanel();
        btnKids1 = new javax.swing.JButton();
        txtKids1 = new javax.swing.JLabel();
        guiaAcompanhamentos = new javax.swing.JTabbedPane();
        painelBebidas = new javax.swing.JPanel();
        btnBebida1 = new javax.swing.JButton();
        txtBebida1 = new javax.swing.JLabel();
        btnBebida2 = new javax.swing.JButton();
        btnBebida3 = new javax.swing.JButton();
        btnBebida4 = new javax.swing.JButton();
        btnBebida5 = new javax.swing.JButton();
        btnBebida6 = new javax.swing.JButton();
        txtBebida2 = new javax.swing.JLabel();
        txtBebida3 = new javax.swing.JLabel();
        txtBebida4 = new javax.swing.JLabel();
        txtBebida5 = new javax.swing.JLabel();
        txtBebida6 = new javax.swing.JLabel();
        painelAcompanhamentos = new javax.swing.JPanel();
        btnAcompanhamento1 = new javax.swing.JButton();
        btnAcompanhamento2 = new javax.swing.JButton();
        btnAcompanhamento3 = new javax.swing.JButton();
        txtAcompanhamentos1 = new javax.swing.JLabel();
        txtAcompanhamentos2 = new javax.swing.JLabel();
        txtAcompanhamentos3 = new javax.swing.JLabel();
        painelSobremesas = new javax.swing.JPanel();
        btnSobremesa1 = new javax.swing.JButton();
        btnSobremesa2 = new javax.swing.JButton();
        txtSobremesa1 = new javax.swing.JLabel();
        txtSobremesa2 = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();
        btnFinalizar = new javax.swing.JButton();
        btnLimparTela = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guiaHamburg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        painelCarne.setBackground(new java.awt.Color(80, 35, 20));
        painelCarne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCarne2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCarne2.setForeground(new java.awt.Color(80, 35, 20));
        btnCarne2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hb2.png"))); // NOI18N
        btnCarne2.setText("HamburgCarne2");
        btnCarne2.setToolTipText("HamburgCarne2");
        btnCarne2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarne2.setName("HamburgCarne2"); // NOI18N
        btnCarne2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCarne2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCarne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarne2ActionPerformed(evt);
            }
        });
        painelCarne.add(btnCarne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 160, 100));

        btnCarne3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCarne3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hb3.png"))); // NOI18N
        btnCarne3.setText("HamburgCarne3");
        btnCarne3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarne3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCarne3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCarne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarne3ActionPerformed(evt);
            }
        });
        painelCarne.add(btnCarne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 149, 114));

        btnCarne1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCarne1.setForeground(new java.awt.Color(80, 35, 20));
        btnCarne1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hb1.png"))); // NOI18N
        btnCarne1.setText("HamburgCarne1");
        btnCarne1.setToolTipText("HamburgCarne1");
        btnCarne1.setActionCommand("");
        btnCarne1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarne1.setHideActionText(true);
        btnCarne1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarne1.setInheritsPopupMenu(true);
        btnCarne1.setName("HamburgCarne1"); // NOI18N
        btnCarne1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCarne1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCarne1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnCarne1StateChanged(evt);
            }
        });
        btnCarne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarne1ActionPerformed(evt);
            }
        });
        painelCarne.add(btnCarne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 38, 149, 100));

        txtCarne1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCarne1.setForeground(new java.awt.Color(255, 255, 255));
        txtCarne1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCarne1.setText("15.00");
        painelCarne.add(txtCarne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 149, 20));

        txtCarne2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCarne2.setForeground(new java.awt.Color(255, 255, 255));
        txtCarne2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCarne2.setText("10.00");
        painelCarne.add(txtCarne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 149, 20));

        txtCarne3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCarne3.setForeground(new java.awt.Color(255, 255, 255));
        txtCarne3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCarne3.setText("12.00");
        painelCarne.add(txtCarne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 149, 20));

        btnCarne7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCarne7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hb7.png"))); // NOI18N
        btnCarne7.setText("HamburgCarne7");
        btnCarne7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarne7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCarne7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCarne7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarne7ActionPerformed(evt);
            }
        });
        painelCarne.add(btnCarne7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 149, 114));

        btnCarne4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCarne4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hb4.png"))); // NOI18N
        btnCarne4.setText("HamburgCarne4");
        btnCarne4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarne4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCarne4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCarne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarne4ActionPerformed(evt);
            }
        });
        painelCarne.add(btnCarne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 149, 114));

        btnCarne6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCarne6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hb6.png"))); // NOI18N
        btnCarne6.setText("HamburgCarne6");
        btnCarne6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarne6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCarne6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCarne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarne6ActionPerformed(evt);
            }
        });
        painelCarne.add(btnCarne6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 149, 114));

        btnCarne5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCarne5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hb5.png"))); // NOI18N
        btnCarne5.setText("HamburgCarne5");
        btnCarne5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarne5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCarne5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCarne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarne5ActionPerformed(evt);
            }
        });
        painelCarne.add(btnCarne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 149, 114));

        btnCarne8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCarne8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hb8.png"))); // NOI18N
        btnCarne8.setText("HamburgCarne8");
        btnCarne8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarne8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCarne8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCarne8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarne8ActionPerformed(evt);
            }
        });
        painelCarne.add(btnCarne8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 149, 114));

        txtCarne4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCarne4.setForeground(new java.awt.Color(255, 255, 255));
        txtCarne4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCarne4.setText("14.00");
        painelCarne.add(txtCarne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 149, 20));

        txtCarne5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCarne5.setForeground(new java.awt.Color(255, 255, 255));
        txtCarne5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCarne5.setText("12.50");
        painelCarne.add(txtCarne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 149, 20));

        txtCarne6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCarne6.setForeground(new java.awt.Color(255, 255, 255));
        txtCarne6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCarne6.setText("9.00");
        painelCarne.add(txtCarne6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 149, 20));

        txtCarne7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCarne7.setForeground(new java.awt.Color(255, 255, 255));
        txtCarne7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCarne7.setText("8.50");
        painelCarne.add(txtCarne7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 149, 20));

        txtCarne8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCarne8.setForeground(new java.awt.Color(255, 255, 255));
        txtCarne8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCarne8.setText("7.00");
        painelCarne.add(txtCarne8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 149, 20));

        btnCarne9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCarne9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hb9.png"))); // NOI18N
        btnCarne9.setText("HamburgCarne9");
        btnCarne9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarne9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCarne9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCarne9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarne9ActionPerformed(evt);
            }
        });
        painelCarne.add(btnCarne9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 149, 114));

        btnCarne10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCarne10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hb10.png"))); // NOI18N
        btnCarne10.setText("HamburgCarne10");
        btnCarne10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarne10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCarne10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCarne10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarne10ActionPerformed(evt);
            }
        });
        painelCarne.add(btnCarne10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 149, 114));

        txtCarne9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCarne9.setForeground(new java.awt.Color(255, 255, 255));
        txtCarne9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCarne9.setText("15.00");
        painelCarne.add(txtCarne9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 740, 149, 20));

        txtCarne10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCarne10.setForeground(new java.awt.Color(255, 255, 255));
        txtCarne10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCarne10.setText("12.00");
        painelCarne.add(txtCarne10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 740, 149, 20));

        guiaHamburg.addTab("Carne", painelCarne);

        painelFrango.setBackground(new java.awt.Color(255, 135, 50));
        painelFrango.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFrango1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFrango1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hf1.png"))); // NOI18N
        btnFrango1.setText("HamburgFrango1");
        btnFrango1.setToolTipText("HamburgFrango1");
        btnFrango1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFrango1.setName("HamburgFrango1"); // NOI18N
        btnFrango1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnFrango1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnFrango1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrango1ActionPerformed(evt);
            }
        });
        painelFrango.add(btnFrango1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 49, 150, 114));

        btnFrango2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFrango2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hf2.png"))); // NOI18N
        btnFrango2.setText("HamburgFrango2");
        btnFrango2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFrango2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnFrango2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnFrango2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrango2ActionPerformed(evt);
            }
        });
        painelFrango.add(btnFrango2, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 49, 150, 114));

        btnFrango3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFrango3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hf3.png"))); // NOI18N
        btnFrango3.setText("HamburgFrango3");
        btnFrango3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFrango3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnFrango3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnFrango3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrango3ActionPerformed(evt);
            }
        });
        painelFrango.add(btnFrango3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 206, 150, 114));

        txtHamburgFrango1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHamburgFrango1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHamburgFrango1.setText("18.40");
        painelFrango.add(txtHamburgFrango1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 20));

        txtHamburgFrango2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHamburgFrango2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHamburgFrango2.setText("15.60");
        painelFrango.add(txtHamburgFrango2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 150, 20));

        txtHamburgFrango3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHamburgFrango3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHamburgFrango3.setText("9.90");
        painelFrango.add(txtHamburgFrango3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 20));

        guiaHamburg.addTab("Frango", painelFrango);

        painelSemCarne.setBackground(new java.awt.Color(25, 135, 55));
        painelSemCarne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSemCarne1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSemCarne1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vg1.png"))); // NOI18N
        btnSemCarne1.setText("SemCarne1");
        btnSemCarne1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSemCarne1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnSemCarne1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnSemCarne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemCarne1ActionPerformed(evt);
            }
        });
        painelSemCarne.add(btnSemCarne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 100));

        txtSemCarne1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSemCarne1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSemCarne1.setText("20.90");
        painelSemCarne.add(txtSemCarne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 20));

        guiaHamburg.addTab("Sem Carne", painelSemCarne);

        painelKids.setBackground(new java.awt.Color(214, 35, 0));
        painelKids.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKids1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKids1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/kd1.png"))); // NOI18N
        btnKids1.setText("Kids1");
        btnKids1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKids1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnKids1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnKids1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKids1ActionPerformed(evt);
            }
        });
        painelKids.add(btnKids1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 100));

        txtKids1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtKids1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtKids1.setText("13.90");
        painelKids.add(txtKids1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, 20));

        guiaHamburg.addTab("Kids", painelKids);

        getContentPane().add(guiaHamburg, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 11, 466, 867));

        guiaAcompanhamentos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        painelBebidas.setBackground(new java.awt.Color(214, 35, 0));
        painelBebidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBebida1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBebida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/b1.png"))); // NOI18N
        btnBebida1.setText("Bebida1");
        btnBebida1.setToolTipText("Bebida1");
        btnBebida1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBebida1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBebida1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBebida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebida1ActionPerformed(evt);
            }
        });
        painelBebidas.add(btnBebida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 100));

        txtBebida1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBebida1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBebida1.setText("2.50");
        painelBebidas.add(txtBebida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 160, 20));

        btnBebida2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBebida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/b2.png"))); // NOI18N
        btnBebida2.setText("Bebida2");
        btnBebida2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBebida2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBebida2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBebida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebida2ActionPerformed(evt);
            }
        });
        painelBebidas.add(btnBebida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 160, 100));

        btnBebida3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBebida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/b3.png"))); // NOI18N
        btnBebida3.setText("Bebida3");
        btnBebida3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBebida3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBebida3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBebida3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebida3ActionPerformed(evt);
            }
        });
        painelBebidas.add(btnBebida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, 100));

        btnBebida4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBebida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/b4.png"))); // NOI18N
        btnBebida4.setText("Bebida4");
        btnBebida4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBebida4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBebida4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBebida4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebida4ActionPerformed(evt);
            }
        });
        painelBebidas.add(btnBebida4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 160, 100));

        btnBebida5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBebida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/b5.png"))); // NOI18N
        btnBebida5.setText("Bebida5");
        btnBebida5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBebida5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBebida5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBebida5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebida5ActionPerformed(evt);
            }
        });
        painelBebidas.add(btnBebida5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 160, 100));

        btnBebida6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBebida6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/b6.png"))); // NOI18N
        btnBebida6.setText("Bebida6");
        btnBebida6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBebida6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBebida6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBebida6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebida6ActionPerformed(evt);
            }
        });
        painelBebidas.add(btnBebida6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 160, 100));

        txtBebida2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBebida2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBebida2.setText("4.00");
        painelBebidas.add(txtBebida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 160, 20));

        txtBebida3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBebida3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBebida3.setText("6.00");
        painelBebidas.add(txtBebida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, 20));

        txtBebida4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBebida4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBebida4.setText("6.00");
        painelBebidas.add(txtBebida4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 160, 20));

        txtBebida5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBebida5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBebida5.setText("4.50");
        painelBebidas.add(txtBebida5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 160, 20));

        txtBebida6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBebida6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBebida6.setText("13.90");
        painelBebidas.add(txtBebida6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 160, 20));

        guiaAcompanhamentos.addTab("Bebidas", painelBebidas);

        painelAcompanhamentos.setBackground(new java.awt.Color(214, 35, 0));
        painelAcompanhamentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcompanhamento1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAcompanhamento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ac1.png"))); // NOI18N
        btnAcompanhamento1.setText("Acompanhamento1");
        btnAcompanhamento1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcompanhamento1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAcompanhamento1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAcompanhamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcompanhamento1ActionPerformed(evt);
            }
        });
        painelAcompanhamentos.add(btnAcompanhamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 150, 114));

        btnAcompanhamento2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAcompanhamento2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ac2.png"))); // NOI18N
        btnAcompanhamento2.setText("Acompanhamento2");
        btnAcompanhamento2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcompanhamento2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAcompanhamento2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAcompanhamento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcompanhamento2ActionPerformed(evt);
            }
        });
        painelAcompanhamentos.add(btnAcompanhamento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 49, 150, 114));

        btnAcompanhamento3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAcompanhamento3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ac3.png"))); // NOI18N
        btnAcompanhamento3.setText("Acompanhamento3");
        btnAcompanhamento3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcompanhamento3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAcompanhamento3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAcompanhamento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcompanhamento3ActionPerformed(evt);
            }
        });
        painelAcompanhamentos.add(btnAcompanhamento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 206, 150, 114));

        txtAcompanhamentos1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAcompanhamentos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAcompanhamentos1.setText("6.90");
        painelAcompanhamentos.add(txtAcompanhamentos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 20));

        txtAcompanhamentos2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAcompanhamentos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAcompanhamentos2.setText("9.90");
        painelAcompanhamentos.add(txtAcompanhamentos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 150, 20));

        txtAcompanhamentos3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAcompanhamentos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAcompanhamentos3.setText("6.00");
        painelAcompanhamentos.add(txtAcompanhamentos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 20));

        guiaAcompanhamentos.addTab("Acompanhamentos", painelAcompanhamentos);

        painelSobremesas.setBackground(new java.awt.Color(255, 170, 0));
        painelSobremesas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSobremesa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSobremesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sv1.png"))); // NOI18N
        btnSobremesa1.setText("Sobremesa1");
        btnSobremesa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSobremesa1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnSobremesa1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnSobremesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobremesa1ActionPerformed(evt);
            }
        });
        painelSobremesas.add(btnSobremesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 150, 114));

        btnSobremesa2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSobremesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sv2.png"))); // NOI18N
        btnSobremesa2.setText("Sobremesa2");
        btnSobremesa2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSobremesa2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnSobremesa2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnSobremesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobremesa2ActionPerformed(evt);
            }
        });
        painelSobremesas.add(btnSobremesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 49, 150, 114));

        txtSobremesa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSobremesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSobremesa1.setText("2.50");
        painelSobremesas.add(txtSobremesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 20));

        txtSobremesa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSobremesa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSobremesa2.setText("4.00");
        painelSobremesas.add(txtSobremesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 150, 20));

        guiaAcompanhamentos.addTab("Sobremesas", painelSobremesas);

        getContentPane().add(guiaAcompanhamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1006, 11, 466, 867));

        btnRemover.setBackground(new java.awt.Color(255, 0, 51));
        btnRemover.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(255, 255, 255));
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 705, 100, 42));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 635, 75, 43));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 635, 105, 40));

        jTProdutos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTProdutos.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 41, 490, 561));

        btnFinalizar.setBackground(new java.awt.Color(0, 102, 102));
        btnFinalizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setText("Finalizar Pedido");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 766, 498, 50));

        btnLimparTela.setBackground(new java.awt.Color(255, 0, 0));
        btnLimparTela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparTela.setForeground(new java.awt.Color(255, 255, 255));
        btnLimparTela.setText("Limpar Tela");
        btnLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTelaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimparTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 706, 101, 42));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("R$");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 630, 40, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCarne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarne1ActionPerformed
        String nome = btnCarne1.getText();
        float valor = Float.parseFloat(txtCarne1.getText());
        adicionarProduto(nome,valor);    
    }//GEN-LAST:event_btnCarne1ActionPerformed

    private void btnCarne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarne2ActionPerformed
        String nome = btnCarne2.getText();
        float valor = Float.parseFloat(txtCarne2.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnCarne2ActionPerformed

    private void btnCarne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarne3ActionPerformed
        String nome = btnCarne3.getText();
        float valor = Float.parseFloat(txtCarne3.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnCarne3ActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (jTProdutos.getSelectedRow() != -1){
            tableModel.removeRow(jTProdutos.getSelectedRow());
        }
        subtrairTotal();  
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnCarne1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnCarne1StateChanged
        
    }//GEN-LAST:event_btnCarne1StateChanged

    private void btnLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTelaActionPerformed
        tableModel.clear();
        lblTotal.setText("0");
    }//GEN-LAST:event_btnLimparTelaActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        if(lblTotal.getText() == "0"){
            JOptionPane.showMessageDialog(null, "Adicione um Produto para prosseguir!");
        }else{
            total = lblTotal.getText();
            TelaFinalizarPedido tFP = new TelaFinalizarPedido();
            tFP.setVisible(true);
            
        }
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnCarne7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarne7ActionPerformed
        String nome = btnCarne7.getText();
        float valor = Float.parseFloat(txtCarne7.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnCarne7ActionPerformed

    private void btnCarne8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarne8ActionPerformed
        String nome = btnCarne8.getText();
        float valor = Float.parseFloat(txtCarne8.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnCarne8ActionPerformed

    private void btnCarne9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarne9ActionPerformed
        String nome = btnCarne9.getText();
        float valor = Float.parseFloat(txtCarne9.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnCarne9ActionPerformed

    private void btnCarne10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarne10ActionPerformed
        String nome = btnCarne10.getText();
        float valor = Float.parseFloat(txtCarne10.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnCarne10ActionPerformed

    private void btnCarne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarne4ActionPerformed
        String nome = btnCarne4.getText();
        float valor = Float.parseFloat(txtCarne4.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnCarne4ActionPerformed

    private void btnCarne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarne5ActionPerformed
        String nome = btnCarne5.getText();
        float valor = Float.parseFloat(txtCarne5.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnCarne5ActionPerformed

    private void btnCarne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarne6ActionPerformed
        String nome = btnCarne6.getText();
        float valor = Float.parseFloat(txtCarne6.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnCarne6ActionPerformed

    private void btnBebida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebida1ActionPerformed
        String nome = btnBebida1.getText();
        float valor = Float.parseFloat(txtBebida1.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnBebida1ActionPerformed

    private void btnBebida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebida2ActionPerformed
        String nome = btnBebida2.getText();
        float valor = Float.parseFloat(txtBebida2.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnBebida2ActionPerformed

    private void btnBebida3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebida3ActionPerformed
        String nome = btnBebida3.getText();
        float valor = Float.parseFloat(txtBebida3.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnBebida3ActionPerformed

    private void btnBebida4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebida4ActionPerformed
        String nome = btnBebida4.getText();
        float valor = Float.parseFloat(txtBebida4.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnBebida4ActionPerformed

    private void btnBebida5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebida5ActionPerformed
        String nome = btnBebida5.getText();
        float valor = Float.parseFloat(txtBebida5.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnBebida5ActionPerformed

    private void btnBebida6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebida6ActionPerformed
        String nome = btnBebida6.getText();
        float valor = Float.parseFloat(txtBebida6.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnBebida6ActionPerformed

    private void btnSemCarne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemCarne1ActionPerformed
        String nome = btnSemCarne1.getText();
        float valor = Float.parseFloat(txtSemCarne1.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnSemCarne1ActionPerformed

    private void btnKids1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKids1ActionPerformed
        String nome = btnKids1.getText();
        float valor = Float.parseFloat(txtKids1.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnKids1ActionPerformed

    private void btnFrango1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrango1ActionPerformed
        String nome = btnFrango1.getText();
        float valor = Float.parseFloat(txtHamburgFrango1.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnFrango1ActionPerformed

    private void btnFrango2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrango2ActionPerformed
        String nome = btnFrango2.getText();
        float valor = Float.parseFloat(txtHamburgFrango2.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnFrango2ActionPerformed

    private void btnFrango3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrango3ActionPerformed
        String nome = btnFrango3.getText();
        float valor = Float.parseFloat(txtHamburgFrango3.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnFrango3ActionPerformed

    private void btnAcompanhamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcompanhamento1ActionPerformed
        String nome = btnAcompanhamento1.getText();
        float valor = Float.parseFloat(txtAcompanhamentos1.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnAcompanhamento1ActionPerformed

    private void btnAcompanhamento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcompanhamento2ActionPerformed
        String nome = btnAcompanhamento2.getText();
        float valor = Float.parseFloat(txtAcompanhamentos2.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnAcompanhamento2ActionPerformed

    private void btnAcompanhamento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcompanhamento3ActionPerformed
        String nome = btnAcompanhamento3.getText();
        float valor = Float.parseFloat(txtAcompanhamentos3.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnAcompanhamento3ActionPerformed

    private void btnSobremesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobremesa1ActionPerformed
        String nome = btnSobremesa1.getText();
        float valor = Float.parseFloat(txtSobremesa1.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnSobremesa1ActionPerformed

    private void btnSobremesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobremesa2ActionPerformed
        String nome = btnSobremesa2.getText();
        float valor = Float.parseFloat(txtSobremesa2.getText());
        adicionarProduto(nome,valor);
    }//GEN-LAST:event_btnSobremesa2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcompanhamento1;
    private javax.swing.JButton btnAcompanhamento2;
    private javax.swing.JButton btnAcompanhamento3;
    private javax.swing.JButton btnBebida1;
    private javax.swing.JButton btnBebida2;
    private javax.swing.JButton btnBebida3;
    private javax.swing.JButton btnBebida4;
    private javax.swing.JButton btnBebida5;
    private javax.swing.JButton btnBebida6;
    private javax.swing.JButton btnCarne1;
    private javax.swing.JButton btnCarne10;
    private javax.swing.JButton btnCarne2;
    private javax.swing.JButton btnCarne3;
    private javax.swing.JButton btnCarne4;
    private javax.swing.JButton btnCarne5;
    private javax.swing.JButton btnCarne6;
    private javax.swing.JButton btnCarne7;
    private javax.swing.JButton btnCarne8;
    private javax.swing.JButton btnCarne9;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnFrango1;
    private javax.swing.JButton btnFrango2;
    private javax.swing.JButton btnFrango3;
    private javax.swing.JButton btnKids1;
    private javax.swing.JButton btnLimparTela;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSemCarne1;
    private javax.swing.JButton btnSobremesa1;
    private javax.swing.JButton btnSobremesa2;
    private javax.swing.JTabbedPane guiaAcompanhamentos;
    private javax.swing.JTabbedPane guiaHamburg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProdutos;
    public javax.swing.JLabel lblTotal;
    private javax.swing.JPanel painelAcompanhamentos;
    private javax.swing.JPanel painelBebidas;
    private javax.swing.JPanel painelCarne;
    private javax.swing.JPanel painelFrango;
    private javax.swing.JPanel painelKids;
    private javax.swing.JPanel painelSemCarne;
    private javax.swing.JPanel painelSobremesas;
    private javax.swing.JLabel txtAcompanhamentos1;
    private javax.swing.JLabel txtAcompanhamentos2;
    private javax.swing.JLabel txtAcompanhamentos3;
    private javax.swing.JLabel txtBebida1;
    private javax.swing.JLabel txtBebida2;
    private javax.swing.JLabel txtBebida3;
    private javax.swing.JLabel txtBebida4;
    private javax.swing.JLabel txtBebida5;
    private javax.swing.JLabel txtBebida6;
    private javax.swing.JLabel txtCarne1;
    private javax.swing.JLabel txtCarne10;
    private javax.swing.JLabel txtCarne2;
    private javax.swing.JLabel txtCarne3;
    private javax.swing.JLabel txtCarne4;
    private javax.swing.JLabel txtCarne5;
    private javax.swing.JLabel txtCarne6;
    private javax.swing.JLabel txtCarne7;
    private javax.swing.JLabel txtCarne8;
    private javax.swing.JLabel txtCarne9;
    private javax.swing.JLabel txtHamburgFrango1;
    private javax.swing.JLabel txtHamburgFrango2;
    private javax.swing.JLabel txtHamburgFrango3;
    private javax.swing.JLabel txtKids1;
    private javax.swing.JLabel txtSemCarne1;
    private javax.swing.JLabel txtSobremesa1;
    private javax.swing.JLabel txtSobremesa2;
    // End of variables declaration//GEN-END:variables
}
